sudo: false
dist: trusty
language: cpp
cache: apt

git:
  depth: 1

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - valgrind
            - cmake
            - cmake-data
      env:
        - COMPILER=g++-5
        - NO_EXCEPTIONS=OFF

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - valgrind
            - cmake
            - cmake-data
      env:
        - COMPILER=g++-6
        - NO_EXCEPTIONS=OFF

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - valgrind
            - cmake
            - cmake-data
      env:
        - COMPILER=g++-6
        - NO_EXCEPTIONS=ON

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - valgrind
            - cmake
            - cmake-data
      env:
        - COMPILER=clang++
        - NO_EXCEPTIONS=OFF

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - g++-6
            - clang-5.0
            - valgrind
            - cmake
            - cmake-data
      env:
        - COMPILER=clang++-5.0
        - NO_EXCEPTIONS=OFF

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - g++-6
            - clang-5.0
            - valgrind
            - cmake
            - cmake-data
      env:
        - COMPILER=clang++-5.0
        - NO_EXCEPTIONS=ON

install:
  - export CXX=$COMPILER
  - $CXX --version

  - mkdir bin
  - cd bin
  - cmake .. -DCMAKE_CXX_FLAGS="-Werror" -DCMAKE_BUILD_TYPE=Release -DTESTS_NO_EXCEPTIONS=$NO_EXCEPTIONS -DTESTS_NO_DEATH_TESTS=ON

script:
  - make -j2
  - valgrind --error-exitcode=1 --leak-check=full --show-reachable=yes ./test/function2_tests
